---
title: "Final Project"
author: "Josie Whittington"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
#install.packages("datasets")
#install.packages("psych")
#install.packages("dplyr")
#install.packages("tidyverse")
#install.packages("ggpubr")
#install.packages("rstatix")
#install.packages("sjPlot")
library(datasets)
library(psych)
library(dplyr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(sjPlot)
library(psych)

mydata <- read_csv("FinalProjectDatac-1f.csv")
```

1c
```{r}
psych::describe(mydata,check=TRUE, na.rm=TRUE)
```
```{r}
describeBy(mydata, group = mydata$Department)
```
1d

Assumptions:
```{r}
#outliers
source("https://goo.gl/4mthoF")
outlierKD(mydata, DailyRate)
```

```{r}
#normality
model  <- lm(DailyRate ~ Department, data = mydata)
ggqqplot(residuals(model))
shapiro_test(residuals(model))
```

```{r}
#homogeneity of variance
mydata %>% levene_test(mydata$DailyRate ~ mydata$Department)
```

ANOVA
```{r}
res.aov <- mydata %>%  anova_test(DailyRate ~ Department)
res.aov
```

```{r}
posthoc <- mydata %>% tukey_hsd(DailyRate ~ Department)
posthoc
```

1f
```{r}
posthoc <- posthoc %>% add_xy_position(x = "Department")
ggboxplot(mydata, x = "Department", y = "DailyRate") +
  stat_pvalue_manual(posthoc, hide.ns = TRUE) +
  labs(
    subtitle = get_test_label(res.aov, detailed = TRUE),
    caption = get_pwc_label(posthoc)
  )
```


Mediation

Descriptive Statistics
```{r}
describeBy(mydata)
```

correlation
```{r}
job_sal <- cor.test(mydata$JobSatisfaction, mydata$PercentSalaryHike)
job_sal

num_job <- cor.test(mydata$number_project, mydata$JobSatisfaction)
num_job

num_sal <- cor.test(mydata$number_project, mydata$PercentSalaryHike)
num_sal
```

direct effect/path c
```{r}
direct<- lm(PercentSalaryHike ~ JobSatisfaction, data=mydata)
summary(direct)
```

effect of IV on M/path a
```{r}
path_a<- lm(number_project ~ JobSatisfaction, data=mydata)
summary(path_a)
```

path c'
```{r}
mediation_reg <- lm(PercentSalaryHike ~ JobSatisfaction + number_project, data=mydata)
summary(mediation_reg)
```
bootstrapping
```{r}
results = mediate(path_a, mediation_reg, treat= "JobSatisfaction", mediator= "number_project", boot=T)
summary(results)
```


Moderation

descriptive statistics
```{r}
psych::describe(mydata,check=TRUE, na.rm=TRUE)
```

```{r}
age_job <- cor.test(mydata$Age, mydata$JobLevel)
age_job

age_edu <- cor.test(mydata$Age, mydata$Education)
age_edu

edu_job <- cor.test(mydata$Education, mydata$JobLevel)
edu_job

```

Main Effects
```{r}
model1 <- lm(mydata$JobLevel ~ mydata$Age + mydata$Education )
summary(model1)
```

Interaction
```{r}
model2 <- lm(JobLevel ~ Age + Education + Age*Education, data = mydata )
summary(model2)
```

Slopes
```{r}
library(interactions)
probe_interaction(model2, pred = Age, modx = Education, cond.int = TRUE)
```

```{r}
summary(model2)
```

